# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='data.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndata.proto\"Q\n2d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3'
)




_D2C2700_INTELLIGENT_DEV_WIFI_SEND_BOARDCAST_MSG_PH = _descriptor.Descriptor(
  name='d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph',
  full_name='d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph'] = _D2C2700_INTELLIGENT_DEV_WIFI_SEND_BOARDCAST_MSG_PH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph = _reflection.GeneratedProtocolMessageType('d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph', (_message.Message,), {
  'DESCRIPTOR' : _D2C2700_INTELLIGENT_DEV_WIFI_SEND_BOARDCAST_MSG_PH,
  '__module__' : 'data_pb2'
  # @@protoc_insertion_point(class_scope:d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph)
  })
_sym_db.RegisterMessage(d2c2700_intelligent_dev_wifi_send_boardcast_msg_ph)


# @@protoc_insertion_point(module_scope)
